variables:
  CI_TOOL: gitlab-ci
  APT_DEPENDENCIES: "libboost-all-dev doxygen doxygen-latex"
  CMAKE_ADDITIONAL_OPTIONS: "-DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=/usr"
  GIT_DEPENDENCIES: "git@gite.lirmm.fr:multi-contact/EigenQP.git#dev"

before_script:
  - git submodule sync
  - git submodule update --init --recursive
  - ./.jrl-ci/dependencies/eigen-3.2

build_gcc:
  stage: build
  script:
    - ./.jrl-ci/run before_install
    - ./.jrl-ci/run build
    - ./.jrl-ci/run after_success
  tags:
    - GCC

build_gcc_debug:
  stage: build
  script:
    - export CMAKE_ADDITIONAL_OPTIONS="-DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/usr"
    - ./.jrl-ci/run before_install
    - ./.jrl-ci/run build
    - ./.jrl-ci/run after_success
  tags:
    - GCC

build_clang:
  stage: build
  script:
    - ./.jrl-ci/run before_install
    - ./.jrl-ci/run build
    - ./.jrl-ci/run after_success
  tags:
    - clang

stages:
  - build
