variables:
  CI_TOOL: gitlab-ci
  APT_DEPENDENCIES: "libboost-all-dev doxygen doxygen-latex librbdyn-dev libmc-rbdyn-urdf-dev libsch-core-dev"
  CMAKE_ADDITIONAL_OPTIONS: "-DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=/usr -DPYTHON_BINDING=OFF"
  GIT_DEPENDENCIES: "git@gite.lirmm.fr:multi-contact/eigen-lssol.git git@gite.lirmm.fr:multi-contact/mc_rtc_ros_data git@gite.lirmm.fr:mc-hrp2/hrp2_drc"
  MASTER_PPA: "pierre-gergondet+ppa/multi-contact-unstable"

before_script:
  - git submodule sync
  - git submodule update --init --recursive
  - add-apt-repository ppa:pierre-gergondet+ppa/multi-contact-unstable && apt-get update && apt-get upgrade cmake -qq
  - ./.jrl-ci/dependencies/eigen-3.2

build_gcc:
  stage: build
  script:
    - ./.jrl-ci/run before_install
    - ./.jrl-ci/run build
    - ./.jrl-ci/run after_success
  tags:
    - GCC

build_gcc_debug:
  stage: build
  script:
    - export CMAKE_ADDITIONAL_OPTIONS="-DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/usr -DPYTHON_BINDING=OFF"
    - export APT_DEPENDENCIES="libboost-all-dev doxygen doxygen-latex libtinyxml2-dev"
    - export GIT_DEPENDENCIES="$GIT_DEPENDENCIES jrl-umi3218/SpaceVecAlg jrl-umi3218/RBDyn jrl-umi3218/mc_rbdyn_urdf jrl-umi3218/sch-core"
    - ./.jrl-ci/run before_install
    - ./.jrl-ci/run build
    - ./.jrl-ci/run after_success
  tags:
    - GCC

build_clang:
  stage: build
  script:
    - ./.jrl-ci/run before_install
    - ./.jrl-ci/run build
    - ./.jrl-ci/run after_success
  tags:
    - clang

stages:
  - build
