variables:
  CI_TOOL: gitlab-ci
  APT_DEPENDENCIES: "libboost-all-dev doxygen doxygen-latex libtinyxml2-dev libeigen3-dev"
  CMAKE_ADDITIONAL_OPTIONS: "-DCMAKE_BUILD_TYPE=RelWithDebInfo -DPYTHON_BINDING=OFF"
  GIT_DEPENDENCIES: "jrl-umi3218/SpaceVecAlg jrl-umi3218/RBDyn jrl-umi3218/mc_rbdyn_urdf jrl-umi3218/sch-core git@gite.lirmm.fr:multi-contact/eigen-lssol.git git@gite.lirmm.fr:multi-contact/mc_rtc_ros_data git@gite.lirmm.fr:mc-hrp2/hrp2_drc"
  DEBIAN_FRONTEND: noninteractive

before_script:
  - git submodule sync
  - git submodule update --init --recursive

build_gcc_bionic:
  stage: build
  script:
    - ./.jrl-ci/run before_install
    - ./.jrl-ci/run build
    - ./.jrl-ci/run after_success
  tags:
    - bionic

build_clang_bionic:
  stage: build
  script:
    - apt-get update -qq && apt-get install -qq clang
    - export CC=clang
    - export CXX=clang++
    - ./.jrl-ci/run before_install
    - ./.jrl-ci/run build
    - ./.jrl-ci/run after_success
  tags:
    - bionic

stages:
  - build
